var Language = function () {
    //reference : https://www.w3schools.com/tags/ref_language_codes.asp
    this.language = [
        {"languageName" : 	"Abkhazian"	,"languageCode" :	"ab"},
        {"languageName" : 	"Afar"	,"languageCode" :	"aa"},
        {"languageName" : 	"Afrikaans"	,"languageCode" :	"af"},
        {"languageName" : 	"Akan"	,"languageCode" :	"ak"},
        {"languageName" : 	"Albanian"	,"languageCode" :	"sq"},
        {"languageName" : 	"Amharic"	,"languageCode" :	"am"},
        {"languageName" : 	"Arabic"	,"languageCode" :	"ar"},
        {"languageName" : 	"Aragonese"	,"languageCode" :	"an"},
        {"languageName" : 	"Armenian"	,"languageCode" :	"hy"},
        {"languageName" : 	"Assamese"	,"languageCode" :	"as"},
        {"languageName" : 	"Avaric"	,"languageCode" :	"av"},
        {"languageName" : 	"Avestan"	,"languageCode" :	"ae"},
        {"languageName" : 	"Aymara"	,"languageCode" :	"ay"},
        {"languageName" : 	"Azerbaijani"	,"languageCode" :	"az"},
        {"languageName" : 	"Bambara"	,"languageCode" :	"bm"},
        {"languageName" : 	"Bashkir"	,"languageCode" :	"ba"},
        {"languageName" : 	"Basque"	,"languageCode" :	"eu"},
        {"languageName" : 	"Belarusian"	,"languageCode" :	"be"},
        {"languageName" : 	"Bengali (Bangla)"	,"languageCode" :	"bn"},
        {"languageName" : 	"Bihari"	,"languageCode" :	"bh"},
        {"languageName" : 	"Bislama"	,"languageCode" :	"bi"},
        {"languageName" : 	"Bosnian"	,"languageCode" :	"bs"},
        {"languageName" : 	"Breton"	,"languageCode" :	"br"},
        {"languageName" : 	"Bulgarian"	,"languageCode" :	"bg"},
        {"languageName" : 	"Burmese"	,"languageCode" :	"my"},
        {"languageName" : 	"Catalan"	,"languageCode" :	"ca"},
        {"languageName" : 	"Chamorro"	,"languageCode" :	"ch"},
        {"languageName" : 	"Chechen"	,"languageCode" :	"ce"},
        {"languageName" : 	"Chichewa, Chewa, Nyanja"	,"languageCode" :	"ny"},
        {"languageName" : 	"Chinese"	,"languageCode" :	"zh"},
        {"languageName" : 	"Chinese (Simplified)"	,"languageCode" :	"zh-Hans"},
        {"languageName" : 	"Chinese (Traditional)"	,"languageCode" :	"zh-Hant"},
        {"languageName" : 	"Chuvash"	,"languageCode" :	"cv"},
        {"languageName" : 	"Cornish"	,"languageCode" :	"kw"},
        {"languageName" : 	"Corsican"	,"languageCode" :	"co"},
        {"languageName" : 	"Cree"	,"languageCode" :	"cr"},
        {"languageName" : 	"Croatian"	,"languageCode" :	"hr"},
        {"languageName" : 	"Czech"	,"languageCode" :	"cs"},
        {"languageName" : 	"Danish"	,"languageCode" :	"da"},
        {"languageName" : 	"Divehi, Dhivehi, Maldivian"	,"languageCode" :	"dv"},
        {"languageName" : 	"Dutch"	,"languageCode" :	"nl"},
        {"languageName" : 	"Dzongkha"	,"languageCode" :	"dz"},
        {"languageName" : 	"English"	,"languageCode" :	"en"},
        {"languageName" : 	"Esperanto"	,"languageCode" :	"eo"},
        {"languageName" : 	"Estonian"	,"languageCode" :	"et"},
        {"languageName" : 	"Ewe"	,"languageCode" :	"ee"},
        {"languageName" : 	"Faroese"	,"languageCode" :	"fo"},
        {"languageName" : 	"Fijian"	,"languageCode" :	"fj"},
        {"languageName" : 	"Finnish"	,"languageCode" :	"fi"},
        {"languageName" : 	"French"	,"languageCode" :	"fr"},
        {"languageName" : 	"Fula, Fulah, Pulaar, Pular"	,"languageCode" :	"ff"},
        {"languageName" : 	"Galician"	,"languageCode" :	"gl"},
        {"languageName" : 	"Gaelic (Scottish)"	,"languageCode" :	"gd"},
        {"languageName" : 	"Gaelic (Manx)"	,"languageCode" :	"gv"},
        {"languageName" : 	"Georgian"	,"languageCode" :	"ka"},
        {"languageName" : 	"German"	,"languageCode" :	"de"},
        {"languageName" : 	"Greek"	,"languageCode" :	"el"},
        {"languageName" : 	"Greenlandic"	,"languageCode" :	"kl"},
        {"languageName" : 	"Guarani"	,"languageCode" :	"gn"},
        {"languageName" : 	"Gujarati"	,"languageCode" :	"gu"},
        {"languageName" : 	"Haitian Creole"	,"languageCode" :	"ht"},
        {"languageName" : 	"Hausa"	,"languageCode" :	"ha"},
        {"languageName" : 	"Hebrew"	,"languageCode" :	"he"},
        {"languageName" : 	"Herero"	,"languageCode" :	"hz"},
        {"languageName" : 	"Hindi"	,"languageCode" :	"hi"},
        {"languageName" : 	"Hiri Motu"	,"languageCode" :	"ho"},
        {"languageName" : 	"Hungarian"	,"languageCode" :	"hu"},
        {"languageName" : 	"Icelandic"	,"languageCode" :	"is"},
        {"languageName" : 	"Ido"	,"languageCode" :	"io"},
        {"languageName" : 	"Igbo"	,"languageCode" :	"ig"},
        {"languageName" : 	"Indonesian"	,"languageCode" :	"id, in"},
        {"languageName" : 	"Interlingua"	,"languageCode" :	"ia"},
        {"languageName" : 	"Interlingue"	,"languageCode" :	"ie"},
        {"languageName" : 	"Inuktitut"	,"languageCode" :	"iu"},
        {"languageName" : 	"Inupiak"	,"languageCode" :	"ik"},
        {"languageName" : 	"Irish"	,"languageCode" :	"ga"},
        {"languageName" : 	"Italian"	,"languageCode" :	"it"},
        {"languageName" : 	"Japanese"	,"languageCode" :	"ja"},
        {"languageName" : 	"Javanese"	,"languageCode" :	"jv"},
        {"languageName" : 	"Kalaallisut, Greenlandic"	,"languageCode" :	"kl"},
        {"languageName" : 	"Kannada"	,"languageCode" :	"kn"},
        {"languageName" : 	"Kanuri"	,"languageCode" :	"kr"},
        {"languageName" : 	"Kashmiri"	,"languageCode" :	"ks"},
        {"languageName" : 	"Kazakh"	,"languageCode" :	"kk"},
        {"languageName" : 	"Khmer"	,"languageCode" :	"km"},
        {"languageName" : 	"Kikuyu"	,"languageCode" :	"ki"},
        {"languageName" : 	"Kinyarwanda (Rwanda)"	,"languageCode" :	"rw"},
        {"languageName" : 	"Kirundi"	,"languageCode" :	"rn"},
        {"languageName" : 	"Kyrgyz"	,"languageCode" :	"ky"},
        {"languageName" : 	"Komi"	,"languageCode" :	"kv"},
        {"languageName" : 	"Kongo"	,"languageCode" :	"kg"},
        {"languageName" : 	"Korean"	,"languageCode" :	"ko"},
        {"languageName" : 	"Kurdish"	,"languageCode" :	"ku"},
        {"languageName" : 	"Kwanyama"	,"languageCode" :	"kj"},
        {"languageName" : 	"Lao"	,"languageCode" :	"lo"},
        {"languageName" : 	"Latin"	,"languageCode" :	"la"},
        {"languageName" : 	"Latvian (Lettish)"	,"languageCode" :	"lv"},
        {"languageName" : 	"Limburgish ( Limburger)"	,"languageCode" :	"li"},
        {"languageName" : 	"Lingala"	,"languageCode" :	"ln"},
        {"languageName" : 	"Lithuanian"	,"languageCode" :	"lt"},
        {"languageName" : 	"Luga-Katanga"	,"languageCode" :	"lu"},
        {"languageName" : 	"Luganda, Ganda"	,"languageCode" :	"lg"},
        {"languageName" : 	"Luxembourgish"	,"languageCode" :	"lb"},
        {"languageName" : 	"Manx"	,"languageCode" :	"gv"},
        {"languageName" : 	"Macedonian"	,"languageCode" :	"mk"},
        {"languageName" : 	"Malagasy"	,"languageCode" :	"mg"},
        {"languageName" : 	"Malay"	,"languageCode" :	"ms"},
        {"languageName" : 	"Malayalam"	,"languageCode" :	"ml"},
        {"languageName" : 	"Maltese"	,"languageCode" :	"mt"},
        {"languageName" : 	"Maori"	,"languageCode" :	"mi"},
        {"languageName" : 	"Marathi"	,"languageCode" :	"mr"},
        {"languageName" : 	"Marshallese"	,"languageCode" :	"mh"},
        {"languageName" : 	"Moldavian"	,"languageCode" :	"mo"},
        {"languageName" : 	"Mongolian"	,"languageCode" :	"mn"},
        {"languageName" : 	"Nauru"	,"languageCode" :	"na"},
        {"languageName" : 	"Navajo"	,"languageCode" :	"nv"},
        {"languageName" : 	"Ndonga"	,"languageCode" :	"ng"},
        {"languageName" : 	"Northern Ndebele"	,"languageCode" :	"nd"},
        {"languageName" : 	"Nepali"	,"languageCode" :	"ne"},
        {"languageName" : 	"Norwegian"	,"languageCode" :	"no"},
        {"languageName" : 	"Norwegian bokmål"	,"languageCode" :	"nb"},
        {"languageName" : 	"Norwegian nynorsk"	,"languageCode" :	"nn"},
        {"languageName" : 	"Nuosu"	,"languageCode" :	"ii"},
        {"languageName" : 	"Occitan"	,"languageCode" :	"oc"},
        {"languageName" : 	"Ojibwe"	,"languageCode" :	"oj"},
        {"languageName" : 	"Old Church Slavonic, Old Bulgarian"	,"languageCode" :	"cu"},
        {"languageName" : 	"Oriya"	,"languageCode" :	"or"},
        {"languageName" : 	"Oromo (Afaan Oromo)"	,"languageCode" :	"om"},
        {"languageName" : 	"Ossetian"	,"languageCode" :	"os"},
        {"languageName" : 	"Pāli"	,"languageCode" :	"pi"},
        {"languageName" : 	"Pashto, Pushto"	,"languageCode" :	"ps"},
        {"languageName" : 	"Persian (Farsi)"	,"languageCode" :	"fa"},
        {"languageName" : 	"Polish"	,"languageCode" :	"pl"},
        {"languageName" : 	"Portuguese"	,"languageCode" :	"pt"},
        {"languageName" : 	"Punjabi (Eastern)"	,"languageCode" :	"pa"},
        {"languageName" : 	"Quechua"	,"languageCode" :	"qu"},
        {"languageName" : 	"Romansh"	,"languageCode" :	"rm"},
        {"languageName" : 	"Romanian"	,"languageCode" :	"ro"},
        {"languageName" : 	"Russian"	,"languageCode" :	"ru"},
        {"languageName" : 	"Sami"	,"languageCode" :	"se"},
        {"languageName" : 	"Samoan"	,"languageCode" :	"sm"},
        {"languageName" : 	"Sango"	,"languageCode" :	"sg"},
        {"languageName" : 	"Sanskrit"	,"languageCode" :	"sa"},
        {"languageName" : 	"Serbian"	,"languageCode" :	"sr"},
        {"languageName" : 	"Serbo-Croatian"	,"languageCode" :	"sh"},
        {"languageName" : 	"Sesotho"	,"languageCode" :	"st"},
        {"languageName" : 	"Setswana"	,"languageCode" :	"tn"},
        {"languageName" : 	"Shona"	,"languageCode" :	"sn"},
        {"languageName" : 	"Sichuan Yi"	,"languageCode" :	"ii"},
        {"languageName" : 	"Sindhi"	,"languageCode" :	"sd"},
        {"languageName" : 	"Sinhalese"	,"languageCode" :	"si"},
        {"languageName" : 	"Siswati"	,"languageCode" :	"ss"},
        {"languageName" : 	"Slovak"	,"languageCode" :	"sk"},
        {"languageName" : 	"Slovenian"	,"languageCode" :	"sl"},
        {"languageName" : 	"Somali"	,"languageCode" :	"so"},
        {"languageName" : 	"Southern Ndebele"	,"languageCode" :	"nr"},
        {"languageName" : 	"Spanish"	,"languageCode" :	"es"},
        {"languageName" : 	"Sundanese"	,"languageCode" :	"su"},
        {"languageName" : 	"Swahili (Kiswahili)"	,"languageCode" :	"sw"},
        {"languageName" : 	"Swati"	,"languageCode" :	"ss"},
        {"languageName" : 	"Swedish"	,"languageCode" :	"sv"},
        {"languageName" : 	"Tagalog"	,"languageCode" :	"tl"},
        {"languageName" : 	"Tahitian"	,"languageCode" :	"ty"},
        {"languageName" : 	"Tajik"	,"languageCode" :	"tg"},
        {"languageName" : 	"Tamil"	,"languageCode" :	"ta"},
        {"languageName" : 	"Tatar"	,"languageCode" :	"tt"},
        {"languageName" : 	"Telugu"	,"languageCode" :	"te"},
        {"languageName" : 	"Thai"	,"languageCode" :	"th"},
        {"languageName" : 	"Tibetan"	,"languageCode" :	"bo"},
        {"languageName" : 	"Tigrinya"	,"languageCode" :	"ti"},
        {"languageName" : 	"Tonga"	,"languageCode" :	"to"},
        {"languageName" : 	"Tsonga"	,"languageCode" :	"ts"},
        {"languageName" : 	"Turkish"	,"languageCode" :	"tr"},
        {"languageName" : 	"Turkmen"	,"languageCode" :	"tk"},
        {"languageName" : 	"Twi"	,"languageCode" :	"tw"},
        {"languageName" : 	"Uyghur"	,"languageCode" :	"ug"},
        {"languageName" : 	"Ukrainian"	,"languageCode" :	"uk"},
        {"languageName" : 	"Urdu"	,"languageCode" :	"ur"},
        {"languageName" : 	"Uzbek"	,"languageCode" :	"uz"},
        {"languageName" : 	"Venda"	,"languageCode" :	"ve"},
        {"languageName" : 	"Vietnamese"	,"languageCode" :	"vi"},
        {"languageName" : 	"Volapük"	,"languageCode" :	"vo"},
        {"languageName" : 	"Wallon"	,"languageCode" :	"wa"},
        {"languageName" : 	"Welsh"	,"languageCode" :	"cy"},
        {"languageName" : 	"Wolof"	,"languageCode" :	"wo"},
        {"languageName" : 	"Western Frisian"	,"languageCode" :	"fy"},
        {"languageName" : 	"Xhosa"	,"languageCode" :	"xh"},
        {"languageName" : 	"Yiddish"	,"languageCode" :	"yi, ji"},
        {"languageName" : 	"Yoruba"	,"languageCode" :	"yo"},
        {"languageName" : 	"Zhuang, Chuang"	,"languageCode" :	"za"},
        {"languageName" : 	"Zulu"	,"languageCode" :	"zu"}
    ];

    /**
     * language json array 가져오는 함수
     */
    this.getLanguageJsonArray = function () {
        return this.language;
    };

    this.getConvertToJson = function (csvData) {
        var lineArray = csvData.split(/\r?\n|\r/);
        var headerArray;
        var resultJson = {};
        $.each(lineArray, function (idx, obj) {
            if(idx == 0){
                headerArray = lineArray[idx].split(',');
            }else{
                var bodyArray = lineArray[idx].split(',');
                $.each(bodyArray, function (bidx, bobj) {
                    if(bidx == 0){
                        if(typeof resultJson[bobj]== "undefined"){
                            resultJson[bobj] = {};
                            $.each(headerArray, function (hidx, hobj) {
                                if(hidx != 0){
                                    resultJson[bobj][hobj] = bodyArray[hidx];
                                }
                            });
                        }
                    }
                });
            }
        });

        return resultJson;

    }

};